import type { GameConfig } from "@/types/game";

export const gameRegistry: GameConfig[] = [
  // ─── Phase 1: MVP Games ───
  {
    slug: "bubble-wrap",
    title: "Infinite Bubble Wrap",
    description: "Pop as many bubbles as you can! Each pop earns a point. Simple, satisfying, infinite.",
    category: "chill",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/bubble-wrap.png",
    color: "#00fff5",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "1-3 min",
    difficulty: "easy",
    tags: ["relaxing", "clicker", "satisfying"],
    enabled: true,
  },
  {
    slug: "color-match",
    title: "Color Match",
    description: "Match the color name to the correct color swatch. Speed and accuracy matter!",
    category: "puzzle",
    scoreType: "accuracy",
    renderingMode: "dom",
    thumbnail: "/games/color-match.png",
    color: "#ff2d95",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "2-5 min",
    difficulty: "medium",
    tags: ["brain", "speed", "colors"],
    enabled: true,
  },
  {
    slug: "stack",
    title: "Stack",
    description: "Stack blocks as high as you can. Time your drops perfectly — each miss shrinks the platform.",
    category: "arcade",
    scoreType: "points",
    renderingMode: "canvas",
    thumbnail: "/games/stack.png",
    color: "#39ff14",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "2-5 min",
    difficulty: "medium",
    tags: ["timing", "precision", "arcade"],
    enabled: true,
  },
  {
    slug: "sudoku-lite",
    title: "Sudoku Lite",
    description: "A simplified 4x4 Sudoku. Fill the grid so each row, column, and box has 1-4. Race the clock!",
    category: "puzzle",
    scoreType: "time",
    renderingMode: "dom",
    thumbnail: "/games/sudoku-lite.png",
    color: "#b026ff",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-10 min",
    difficulty: "medium",
    tags: ["logic", "numbers", "puzzle"],
    enabled: true,
  },

  // ─── Phase 3: 6 More Games (disabled until implemented) ───
  {
    slug: "daily-pixel-puzzle",
    title: "Daily Pixel Puzzle",
    description: "Reveal a pixel art image one tile at a time. Guess the image to earn bonus points.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/daily-pixel-puzzle.png",
    color: "#ffe600",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "easy",
    tags: ["daily", "pixel-art", "guessing"],
    enabled: false,
  },
  {
    slug: "lo-fi-typer",
    title: "Lo-Fi Typer",
    description: "Type along to lo-fi beats. Accuracy and speed combine for your score.",
    category: "chill",
    scoreType: "combo",
    renderingMode: "dom",
    thumbnail: "/games/lo-fi-typer.png",
    color: "#00fff5",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "2-5 min",
    difficulty: "medium",
    tags: ["typing", "music", "chill"],
    enabled: false,
  },
  {
    slug: "falling-sand",
    title: "Falling Sand",
    description: "A digital sandbox. Drop sand, water, and fire particles and watch them interact.",
    category: "creative",
    scoreType: "custom",
    renderingMode: "canvas",
    thumbnail: "/games/falling-sand.png",
    color: "#ffe600",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["sandbox", "physics", "creative"],
    enabled: false,
  },
  {
    slug: "syntax-breaker",
    title: "Syntax Breaker",
    description: "Find and fix the syntax errors in code snippets before time runs out.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/syntax-breaker.png",
    color: "#39ff14",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "hard",
    tags: ["coding", "debugging", "speed"],
    enabled: false,
  },
  {
    slug: "constellation-hunter",
    title: "Constellation Hunter",
    description: "Connect stars to form constellations against a ticking clock.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "canvas",
    thumbnail: "/games/constellation-hunter.png",
    color: "#b026ff",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "medium",
    tags: ["stars", "patterns", "spatial"],
    enabled: false,
  },
  {
    slug: "gacha-capsule",
    title: "Gacha Capsule",
    description: "Spend virtual coins on capsule machines. Collect rare items and complete sets!",
    category: "chill",
    scoreType: "custom",
    renderingMode: "dom",
    thumbnail: "/games/gacha-capsule.png",
    color: "#ff2d95",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["collecting", "luck", "gacha"],
    enabled: false,
  },

  // ─── Phase 5: Remaining 8 Games ───
  {
    slug: "zen-garden",
    title: "Zen Garden",
    description: "Rake sand, place stones, and grow a peaceful garden.",
    category: "creative",
    scoreType: "custom",
    renderingMode: "canvas",
    thumbnail: "/games/zen-garden.png",
    color: "#39ff14",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["relaxing", "creative", "zen"],
    enabled: false,
  },
  {
    slug: "workspace-pet",
    title: "Workspace Pet",
    description: "Adopt a virtual pet that lives on your screen. Feed, play, and keep it happy!",
    category: "chill",
    scoreType: "custom",
    renderingMode: "dom",
    thumbnail: "/games/workspace-pet.png",
    color: "#ff2d95",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "ongoing",
    difficulty: "easy",
    tags: ["pet", "tamagotchi", "cute"],
    enabled: false,
  },
  {
    slug: "focus-forest",
    title: "Focus Forest",
    description: "Plant trees by focusing. The longer you stay, the bigger your forest grows.",
    category: "chill",
    scoreType: "time",
    renderingMode: "canvas",
    thumbnail: "/games/focus-forest.png",
    color: "#39ff14",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-25 min",
    difficulty: "easy",
    tags: ["focus", "productivity", "nature"],
    enabled: false,
  },
  {
    slug: "neon-rhythm",
    title: "Neon Rhythm",
    description: "Hit notes to the beat in this neon-styled rhythm game.",
    category: "arcade",
    scoreType: "combo",
    renderingMode: "phaser",
    thumbnail: "/games/neon-rhythm.png",
    color: "#ff2d95",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "hard",
    tags: ["rhythm", "music", "arcade"],
    enabled: false,
  },
  {
    slug: "hexagon-land",
    title: "Hexagon Land",
    description: "Place hexagonal tiles to build a landscape. Match biomes for bonus points.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "phaser",
    thumbnail: "/games/hexagon-land.png",
    color: "#00fff5",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-10 min",
    difficulty: "medium",
    tags: ["strategy", "tiles", "building"],
    enabled: false,
  },
  {
    slug: "one-minute-barista",
    title: "1-Minute Barista",
    description: "Make coffee orders as fast as possible in 60 seconds. Don't mess up the orders!",
    category: "arcade",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/one-minute-barista.png",
    color: "#ffe600",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "1 min",
    difficulty: "hard",
    tags: ["speed", "memory", "arcade"],
    enabled: false,
  },
  {
    slug: "magnetic-poetry",
    title: "Magnetic Poetry",
    description: "Drag word magnets to create poems. Share your creations with the community.",
    category: "creative",
    scoreType: "custom",
    renderingMode: "dom",
    thumbnail: "/games/magnetic-poetry.png",
    color: "#b026ff",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["words", "creative", "social"],
    enabled: false,
  },
  {
    slug: "community-grid",
    title: "Community Grid",
    description: "Place pixels on a shared canvas. Work together to create art!",
    category: "creative",
    scoreType: "custom",
    renderingMode: "canvas",
    thumbnail: "/games/community-grid.png",
    color: "#00fff5",
    minPlayers: 1,
    maxPlayers: 100,
    estimatedPlayTime: "ongoing",
    difficulty: "easy",
    tags: ["multiplayer", "pixel-art", "community"],
    enabled: false,
  },
];

export function getGameBySlug(slug: string): GameConfig | undefined {
  return gameRegistry.find((g) => g.slug === slug);
}

export function getEnabledGames(): GameConfig[] {
  return gameRegistry.filter((g) => g.enabled);
}

export function getGamesByCategory(category: string): GameConfig[] {
  return gameRegistry.filter((g) => g.category === category && g.enabled);
}
