import type { GameConfig } from "@/types/game";

export const gameRegistry: GameConfig[] = [
  // ─── Phase 1: MVP Games ───
  {
    slug: "bubble-wrap",
    title: "Bubble Wrap Blitz",
    description: "Pop as many bubbles as you can in 30 seconds! Each pop earns a point. Fast fingers win!",
    category: "chill",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/bubble-wrap.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "30 sec",
    difficulty: "easy",
    tags: ["relaxing", "clicker", "satisfying", "timed"],
    howToPlay: [
      "Click or tap any bubble to pop it",
      "Each pop earns 1 point",
      "Pop all bubbles to regenerate a fresh grid",
      "You have 30 seconds — pop as many as you can!",
    ],
    enabled: true,
  },
  {
    slug: "color-match",
    title: "Color Match",
    description: "Match the color name to the correct color swatch. Speed and accuracy matter!",
    category: "puzzle",
    scoreType: "accuracy",
    renderingMode: "dom",
    thumbnail: "/games/color-match.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "2-5 min",
    difficulty: "medium",
    tags: ["brain", "speed", "colors"],
    howToPlay: [
      "A color name appears at the top in a misleading color",
      "Click the swatch that matches the WORD, not the text color",
      "Answer quickly for bonus points",
      "Wrong answers lose points — accuracy matters!",
    ],
    enabled: true,
  },
  {
    slug: "stack",
    title: "Stack",
    description: "Stack blocks as high as you can. Time your drops perfectly — each miss shrinks the platform.",
    category: "arcade",
    scoreType: "points",
    renderingMode: "canvas",
    thumbnail: "/games/stack.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "2-5 min",
    difficulty: "medium",
    tags: ["timing", "precision", "arcade"],
    howToPlay: [
      "A block slides back and forth across the screen",
      "Click or press Space to drop it",
      "Only the overlapping portion stays — misalignment shrinks the platform",
      "Miss completely and it's game over",
      "Speed increases as you stack higher",
    ],
    enabled: true,
  },
  {
    slug: "sudoku-lite",
    title: "Sudoku Lite",
    description: "A simplified 4x4 Sudoku. Fill the grid so each row, column, and box has 1-4. Race the clock!",
    category: "puzzle",
    scoreType: "time",
    renderingMode: "dom",
    thumbnail: "/games/sudoku-lite.png",
    color: "#7C3AED",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-10 min",
    difficulty: "medium",
    tags: ["logic", "numbers", "puzzle"],
    howToPlay: [
      "Fill in the empty cells with numbers 1-4",
      "Each row must contain 1, 2, 3, and 4",
      "Each column must contain 1, 2, 3, and 4",
      "Each 2x2 box must contain 1, 2, 3, and 4",
      "Complete the grid as fast as possible — time is your score!",
    ],
    enabled: true,
  },

  // ─── Phase 3: 6 More Games ───
  {
    slug: "daily-pixel-puzzle",
    title: "Daily Pixel Puzzle",
    description: "Reveal a pixel art image one tile at a time. Guess the image to earn bonus points.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/daily-pixel-puzzle.png",
    color: "#CA8A04",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "easy",
    tags: ["daily", "pixel-art", "guessing"],
    howToPlay: [
      "Click tiles on the 8x8 grid to reveal hidden pixel art",
      "Try to guess the image with as few tiles revealed as possible",
      "Choose your answer from 4 options when you think you know it",
      "Fewer reveals = higher score. Correct guess = big bonus!",
    ],
    enabled: true,
  },
  {
    slug: "lo-fi-typer",
    title: "Lo-Fi Typer",
    description: "Type along to lo-fi beats. Accuracy and speed combine for your score.",
    category: "chill",
    scoreType: "combo",
    renderingMode: "dom",
    thumbnail: "/games/lo-fi-typer.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "2-5 min",
    difficulty: "medium",
    tags: ["typing", "music", "chill"],
    howToPlay: [
      "Type the displayed text as accurately as possible",
      "Correct keystrokes build your combo multiplier",
      "Mistakes break your combo — stay focused!",
      "Higher combo = higher score per keystroke",
      "Complete all sentences to finish",
    ],
    enabled: true,
  },
  {
    slug: "falling-sand",
    title: "Falling Sand",
    description: "A digital sandbox. Drop sand, water, and fire particles and watch them interact.",
    category: "creative",
    scoreType: "custom",
    renderingMode: "canvas",
    thumbnail: "/games/falling-sand.png",
    color: "#CA8A04",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["sandbox", "physics", "creative"],
    howToPlay: [
      "Select a particle type: Sand, Water, Fire, or Wall",
      "Click and drag on the canvas to spawn particles",
      "Watch particles interact — sand falls, water flows, fire rises",
      "Build landscapes, dams, and watch the physics play out",
      "No score — just a creative sandbox to experiment in!",
    ],
    enabled: true,
  },
  {
    slug: "syntax-breaker",
    title: "Syntax Breaker",
    description: "Find and fix the syntax errors in code snippets before time runs out.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/syntax-breaker.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "hard",
    tags: ["coding", "debugging", "speed"],
    howToPlay: [
      "Each level shows a code snippet with a syntax error",
      "Find the bug and type the corrected line",
      "Beat the timer to earn points",
      "Errors get trickier as levels progress",
      "Perfect fix = bonus points!",
    ],
    enabled: true,
  },
  {
    slug: "constellation-hunter",
    title: "Constellation Hunter",
    description: "Connect stars to form constellations against a ticking clock.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "canvas",
    thumbnail: "/games/constellation-hunter.png",
    color: "#7C3AED",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "medium",
    tags: ["stars", "patterns", "spatial"],
    howToPlay: [
      "A target constellation pattern is shown at the top",
      "Click stars in the sky to connect them with lines",
      "Recreate the constellation pattern by connecting the right stars",
      "Complete it before time runs out for bonus points",
      "Each constellation solved adds more time",
    ],
    enabled: true,
  },
  {
    slug: "gacha-capsule",
    title: "Gacha Capsule",
    description: "Spend virtual coins on capsule machines. Collect rare items and complete sets!",
    category: "chill",
    scoreType: "custom",
    renderingMode: "dom",
    thumbnail: "/games/gacha-capsule.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["collecting", "luck", "gacha"],
    howToPlay: [
      "Spend coins to pull capsules from the machine",
      "Each capsule contains a random item with a rarity tier",
      "Collect items to complete sets for bonus rewards",
      "Rarer items are harder to find — keep pulling!",
      "Score is based on your collection value",
    ],
    enabled: true,
  },

  // ─── Phase 5: Remaining 8 Games ───
  {
    slug: "zen-garden",
    title: "Zen Garden",
    description: "Rake sand, place stones, and grow a peaceful garden.",
    category: "creative",
    scoreType: "custom",
    renderingMode: "canvas",
    thumbnail: "/games/zen-garden.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["relaxing", "creative", "zen"],
    howToPlay: [
      "Choose a tool: Rake, Stone, or Plant",
      "Rake: Click and drag to draw zen sand patterns",
      "Stone: Click to place decorative stones",
      "Plant: Click to grow trees, bushes, and flowers",
      "Create your perfect zen garden — earn serenity points as you go",
    ],
    enabled: true,
  },
  {
    slug: "workspace-pet",
    title: "Workspace Pet",
    description: "Adopt a virtual pet that lives on your screen. Feed, play, and keep it happy!",
    category: "chill",
    scoreType: "custom",
    renderingMode: "dom",
    thumbnail: "/games/workspace-pet.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "ongoing",
    difficulty: "easy",
    tags: ["pet", "tamagotchi", "cute"],
    howToPlay: [
      "Your pet has 3 stats: Hunger, Happiness, and Energy",
      "Feed: Restores hunger but costs some energy",
      "Play: Boosts happiness but drains energy and hunger",
      "Sleep: Restores energy over time",
      "Pet: Give a quick happiness boost",
      "Keep all stats above zero or it's game over!",
    ],
    enabled: true,
  },
  {
    slug: "focus-forest",
    title: "Focus Forest",
    description: "Plant trees by focusing. The longer you stay, the bigger your forest grows.",
    category: "chill",
    scoreType: "time",
    renderingMode: "canvas",
    thumbnail: "/games/focus-forest.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-25 min",
    difficulty: "easy",
    tags: ["focus", "productivity", "nature"],
    howToPlay: [
      "Start a focus session and watch your tree grow",
      "The tree progresses through 5 stages over 25 minutes",
      "Stay focused — your tree grows as long as you're active",
      "Click 'Harvest' when ready to save your tree to your forest",
      "Your score is total focus time in seconds",
    ],
    enabled: true,
  },
  {
    slug: "neon-rhythm",
    title: "Neon Rhythm",
    description: "Hit notes to the beat in this neon-styled rhythm game.",
    category: "arcade",
    scoreType: "combo",
    renderingMode: "dom",
    thumbnail: "/games/neon-rhythm.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "hard",
    tags: ["rhythm", "music", "arcade"],
    howToPlay: [
      "Notes fall down 4 lanes toward the hit zone",
      "Press D, F, J, or K when notes reach the bottom line",
      "Perfect timing (within 50ms) = 100 points",
      "Good timing (within 100ms) = 50 points",
      "Build combos for score multipliers — every 5 combo adds bonus points",
      "Choose from 3 songs with increasing difficulty",
    ],
    enabled: true,
  },
  {
    slug: "hexagon-land",
    title: "Hexagon Land",
    description: "Place hexagonal tiles to build a landscape. Match biomes for bonus points.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/hexagon-land.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-10 min",
    difficulty: "medium",
    tags: ["strategy", "tiles", "building"],
    howToPlay: [
      "You have 20 hexagonal tiles to place on the grid",
      "Each tile has a random biome: Forest, Water, Mountain, Desert, City, or Farm",
      "Click an empty hex to place your current tile",
      "+1 point per placement, +3 bonus per adjacent matching biome",
      "Plan ahead using the 3-tile preview queue for maximum points",
    ],
    enabled: true,
  },
  {
    slug: "one-minute-barista",
    title: "1-Minute Barista",
    description: "Make coffee orders as fast as possible in 60 seconds. Don't mess up the orders!",
    category: "arcade",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/one-minute-barista.png",
    color: "#CA8A04",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "1 min",
    difficulty: "hard",
    tags: ["speed", "memory", "arcade"],
    howToPlay: [
      "Orders appear at the top — up to 3 at a time",
      "Click ingredient buttons to add them to your cup",
      "Click 'Serve' when your cup matches an order",
      "Correct order = +10 points (+5 speed bonus if under 5 seconds)",
      "Wrong drink = -5 points. Use 'Dump' to start over",
      "Serve as many orders as you can in 60 seconds!",
    ],
    enabled: true,
  },
  {
    slug: "magnetic-poetry",
    title: "Magnetic Poetry",
    description: "Drag word magnets to create poems. Share your creations with the community.",
    category: "creative",
    scoreType: "custom",
    renderingMode: "dom",
    thumbnail: "/games/magnetic-poetry.png",
    color: "#7C3AED",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["words", "creative", "social"],
    howToPlay: [
      "Drag word magnets from the tray onto the fridge board",
      "Arrange words to create poems, phrases, or messages",
      "Move words around by clicking and dragging them",
      "Click 'New Words' to shuffle and get a fresh set",
      "No right or wrong answers — just express yourself!",
    ],
    enabled: true,
  },
  {
    slug: "community-grid",
    title: "Community Grid",
    description: "Place pixels on a shared canvas. Work together to create art!",
    category: "creative",
    scoreType: "custom",
    renderingMode: "canvas",
    thumbnail: "/games/community-grid.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 100,
    estimatedPlayTime: "ongoing",
    difficulty: "easy",
    tags: ["multiplayer", "pixel-art", "community"],
    howToPlay: [
      "Pick a color from the 16-color palette below the canvas",
      "Choose a tool: Pencil (single pixel), Fill (flood fill), or Eraser",
      "Click or drag on the 32x32 grid to place pixels",
      "Use the fill tool to color large areas quickly",
      "Create pixel art, patterns, or collaborate with others!",
    ],
    enabled: true,
  },

  // ─── Phase 6: 3D Racing ───
  {
    slug: "velocity",
    title: "Velocity.js",
    description:
      "Race through neon-lit circuits at breakneck speed. Drift around corners, boost past opponents, and cross the finish line first!",
    category: "arcade",
    scoreType: "time",
    renderingMode: "canvas",
    thumbnail: "/games/velocity.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "medium",
    tags: ["racing", "3d", "arcade", "drift"],
    howToPlay: [
      "W / Arrow Up = Accelerate, S / Arrow Down = Brake",
      "A / Arrow Left = Steer Left, D / Arrow Right = Steer Right",
      "Hold Space while turning to drift — release for a speed boost!",
      "Complete 3 laps around the neon track to finish",
      "Hit boost pads for a burst of speed, avoid barriers!",
      "Your score is your total race time — faster is better",
    ],
    enabled: true,
  },
];

export function getGameBySlug(slug: string): GameConfig | undefined {
  return gameRegistry.find((g) => g.slug === slug);
}

export function getEnabledGames(): GameConfig[] {
  return gameRegistry.filter((g) => g.enabled);
}

export function getGamesByCategory(category: string): GameConfig[] {
  return gameRegistry.filter((g) => g.category === category && g.enabled);
}
