import type { GameConfig } from "@/types/game";

export const gameRegistry: GameConfig[] = [
  // ─── Phase 1: MVP Games ───
  {
    slug: "bubble-wrap",
    title: "Bubble Wrap Blitz",
    description: "Pop as many bubbles as you can in 30 seconds! Each pop earns a point. Fast fingers win!",
    category: "chill",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/bubble-wrap.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "30 sec",
    difficulty: "easy",
    tags: ["relaxing", "clicker", "satisfying", "timed"],
    howToPlay: [
      "Click or tap any bubble to pop it",
      "Each pop earns 1 point",
      "Pop all bubbles to regenerate a fresh grid",
      "You have 30 seconds — pop as many as you can!",
    ],
    enabled: true,
  },
  {
    slug: "color-match",
    title: "Color Match",
    description: "Match the color name to the correct color swatch. Speed and accuracy matter!",
    category: "puzzle",
    scoreType: "accuracy",
    renderingMode: "dom",
    thumbnail: "/games/color-match.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "2-5 min",
    difficulty: "medium",
    tags: ["brain", "speed", "colors"],
    howToPlay: [
      "A color name appears at the top in a misleading color",
      "Click the swatch that matches the WORD, not the text color",
      "Answer quickly for bonus points",
      "Wrong answers lose points — accuracy matters!",
    ],
    enabled: true,
  },
  {
    slug: "stack",
    title: "Stack",
    description: "Stack blocks as high as you can. Time your drops perfectly — each miss shrinks the platform.",
    category: "arcade",
    scoreType: "points",
    renderingMode: "canvas",
    thumbnail: "/games/stack.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "2-5 min",
    difficulty: "medium",
    tags: ["timing", "precision", "arcade"],
    howToPlay: [
      "A block slides back and forth across the screen",
      "Click or press Space to drop it",
      "Only the overlapping portion stays — misalignment shrinks the platform",
      "Miss completely and it's game over",
      "Speed increases as you stack higher",
    ],
    enabled: true,
  },
  {
    slug: "sudoku-lite",
    title: "Sudoku Lite",
    description: "A simplified 4x4 Sudoku. Fill the grid so each row, column, and box has 1-4. Race the clock!",
    category: "puzzle",
    scoreType: "time",
    renderingMode: "dom",
    thumbnail: "/games/sudoku-lite.png",
    color: "#7C3AED",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-10 min",
    difficulty: "medium",
    tags: ["logic", "numbers", "puzzle"],
    howToPlay: [
      "Fill in the empty cells with numbers 1-4",
      "Each row must contain 1, 2, 3, and 4",
      "Each column must contain 1, 2, 3, and 4",
      "Each 2x2 box must contain 1, 2, 3, and 4",
      "Complete the grid as fast as possible — time is your score!",
    ],
    enabled: true,
  },

  // ─── Phase 3: 6 More Games ───
  {
    slug: "daily-pixel-puzzle",
    title: "Daily Pixel Puzzle",
    description: "Reveal a pixel art image one tile at a time. Guess the image to earn bonus points.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/daily-pixel-puzzle.png",
    color: "#CA8A04",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "easy",
    tags: ["daily", "pixel-art", "guessing"],
    howToPlay: [
      "Click tiles on the 8x8 grid to reveal hidden pixel art",
      "Try to guess the image with as few tiles revealed as possible",
      "Choose your answer from 4 options when you think you know it",
      "Fewer reveals = higher score. Correct guess = big bonus!",
    ],
    enabled: true,
  },
  {
    slug: "lo-fi-typer",
    title: "Lo-Fi Typer",
    description: "Type along to lo-fi beats. Accuracy and speed combine for your score.",
    category: "chill",
    scoreType: "combo",
    renderingMode: "dom",
    thumbnail: "/games/lo-fi-typer.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "2-5 min",
    difficulty: "medium",
    tags: ["typing", "music", "chill"],
    howToPlay: [
      "Type the displayed text as accurately as possible",
      "Correct keystrokes build your combo multiplier",
      "Mistakes break your combo — stay focused!",
      "Higher combo = higher score per keystroke",
      "Complete all sentences to finish",
    ],
    enabled: true,
  },
  {
    slug: "falling-sand",
    title: "Falling Sand",
    description: "A digital sandbox. Drop sand, water, and fire particles and watch them interact.",
    category: "creative",
    scoreType: "custom",
    renderingMode: "canvas",
    thumbnail: "/games/falling-sand.png",
    color: "#CA8A04",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["sandbox", "physics", "creative"],
    howToPlay: [
      "Select a particle type: Sand, Water, Fire, or Wall",
      "Click and drag on the canvas to spawn particles",
      "Watch particles interact — sand falls, water flows, fire rises",
      "Build landscapes, dams, and watch the physics play out",
      "No score — just a creative sandbox to experiment in!",
    ],
    enabled: true,
  },
  {
    slug: "syntax-breaker",
    title: "Syntax Breaker",
    description: "Find and fix the syntax errors in code snippets before time runs out.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/syntax-breaker.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "hard",
    tags: ["coding", "debugging", "speed"],
    howToPlay: [
      "Each level shows a code snippet with a syntax error",
      "Find the bug and type the corrected line",
      "Beat the timer to earn points",
      "Errors get trickier as levels progress",
      "Perfect fix = bonus points!",
    ],
    enabled: true,
  },
  {
    slug: "constellation-hunter",
    title: "Constellation Hunter",
    description: "Connect stars to form constellations against a ticking clock.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "canvas",
    thumbnail: "/games/constellation-hunter.png",
    color: "#7C3AED",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "medium",
    tags: ["stars", "patterns", "spatial"],
    howToPlay: [
      "A target constellation pattern is shown at the top",
      "Click stars in the sky to connect them with lines",
      "Recreate the constellation pattern by connecting the right stars",
      "Complete it before time runs out for bonus points",
      "Each constellation solved adds more time",
    ],
    enabled: true,
  },
  {
    slug: "gacha-capsule",
    title: "Gacha Capsule",
    description: "Spend virtual coins on capsule machines. Collect rare items and complete sets!",
    category: "chill",
    scoreType: "custom",
    renderingMode: "dom",
    thumbnail: "/games/gacha-capsule.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["collecting", "luck", "gacha"],
    howToPlay: [
      "Spend coins to pull capsules from the machine",
      "Each capsule contains a random item with a rarity tier",
      "Collect items to complete sets for bonus rewards",
      "Rarer items are harder to find — keep pulling!",
      "Score is based on your collection value",
    ],
    enabled: true,
  },

  // ─── Phase 5: Remaining 8 Games ───
  {
    slug: "zen-garden",
    title: "Zen Garden",
    description: "Rake sand, place stones, and grow a peaceful garden.",
    category: "creative",
    scoreType: "custom",
    renderingMode: "canvas",
    thumbnail: "/games/zen-garden.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["relaxing", "creative", "zen"],
    howToPlay: [
      "Choose a tool: Rake, Stone, or Plant",
      "Rake: Click and drag to draw zen sand patterns",
      "Stone: Click to place decorative stones",
      "Plant: Click to grow trees, bushes, and flowers",
      "Create your perfect zen garden — earn serenity points as you go",
    ],
    enabled: true,
  },
  {
    slug: "workspace-pet",
    title: "Workspace Pet",
    description: "Adopt a virtual pet that lives on your screen. Feed, play, and keep it happy!",
    category: "chill",
    scoreType: "custom",
    renderingMode: "dom",
    thumbnail: "/games/workspace-pet.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "ongoing",
    difficulty: "easy",
    tags: ["pet", "tamagotchi", "cute"],
    howToPlay: [
      "Your pet has 3 stats: Hunger, Happiness, and Energy",
      "Feed: Restores hunger but costs some energy",
      "Play: Boosts happiness but drains energy and hunger",
      "Sleep: Restores energy over time",
      "Pet: Give a quick happiness boost",
      "Keep all stats above zero or it's game over!",
    ],
    enabled: true,
  },
  {
    slug: "focus-forest",
    title: "Focus Forest",
    description: "Plant trees by focusing. The longer you stay, the bigger your forest grows.",
    category: "chill",
    scoreType: "time",
    renderingMode: "canvas",
    thumbnail: "/games/focus-forest.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-25 min",
    difficulty: "easy",
    tags: ["focus", "productivity", "nature"],
    howToPlay: [
      "Start a focus session and watch your tree grow",
      "The tree progresses through 5 stages over 25 minutes",
      "Stay focused — your tree grows as long as you're active",
      "Click 'Harvest' when ready to save your tree to your forest",
      "Your score is total focus time in seconds",
    ],
    enabled: true,
  },
  {
    slug: "neon-rhythm",
    title: "Neon Rhythm",
    description: "Hit notes to the beat in this neon-styled rhythm game.",
    category: "arcade",
    scoreType: "combo",
    renderingMode: "dom",
    thumbnail: "/games/neon-rhythm.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "hard",
    tags: ["rhythm", "music", "arcade"],
    howToPlay: [
      "Notes fall down 4 lanes toward the hit zone",
      "Press D, F, J, or K when notes reach the bottom line",
      "Perfect timing (within 50ms) = 100 points",
      "Good timing (within 100ms) = 50 points",
      "Build combos for score multipliers — every 5 combo adds bonus points",
      "Choose from 3 songs with increasing difficulty",
    ],
    enabled: true,
  },
  {
    slug: "hexagon-land",
    title: "Hexagon Land",
    description: "Place hexagonal tiles to build a landscape. Match biomes for bonus points.",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/hexagon-land.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-10 min",
    difficulty: "medium",
    tags: ["strategy", "tiles", "building"],
    howToPlay: [
      "You have 20 hexagonal tiles to place on the grid",
      "Each tile has a random biome: Forest, Water, Mountain, Desert, City, or Farm",
      "Click an empty hex to place your current tile",
      "+1 point per placement, +3 bonus per adjacent matching biome",
      "Plan ahead using the 3-tile preview queue for maximum points",
    ],
    enabled: true,
  },
  {
    slug: "one-minute-barista",
    title: "1-Minute Barista",
    description: "Make coffee orders as fast as possible in 60 seconds. Don't mess up the orders!",
    category: "arcade",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/one-minute-barista.png",
    color: "#CA8A04",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "1 min",
    difficulty: "hard",
    tags: ["speed", "memory", "arcade"],
    howToPlay: [
      "Orders appear at the top — up to 3 at a time",
      "Click ingredient buttons to add them to your cup",
      "Click 'Serve' when your cup matches an order",
      "Correct order = +10 points (+5 speed bonus if under 5 seconds)",
      "Wrong drink = -5 points. Use 'Dump' to start over",
      "Serve as many orders as you can in 60 seconds!",
    ],
    enabled: true,
  },
  {
    slug: "magnetic-poetry",
    title: "Magnetic Poetry",
    description: "Drag word magnets to create poems. Share your creations with the community.",
    category: "creative",
    scoreType: "custom",
    renderingMode: "dom",
    thumbnail: "/games/magnetic-poetry.png",
    color: "#7C3AED",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5+ min",
    difficulty: "easy",
    tags: ["words", "creative", "social"],
    howToPlay: [
      "Drag word magnets from the tray onto the fridge board",
      "Arrange words to create poems, phrases, or messages",
      "Move words around by clicking and dragging them",
      "Click 'New Words' to shuffle and get a fresh set",
      "No right or wrong answers — just express yourself!",
    ],
    enabled: true,
  },
  {
    slug: "community-grid",
    title: "Community Grid",
    description: "Place pixels on a shared canvas. Work together to create art!",
    category: "creative",
    scoreType: "custom",
    renderingMode: "canvas",
    thumbnail: "/games/community-grid.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 100,
    estimatedPlayTime: "ongoing",
    difficulty: "easy",
    tags: ["multiplayer", "pixel-art", "community"],
    howToPlay: [
      "Pick a color from the 16-color palette below the canvas",
      "Choose a tool: Pencil (single pixel), Fill (flood fill), or Eraser",
      "Click or drag on the 32x32 grid to place pixels",
      "Use the fill tool to color large areas quickly",
      "Create pixel art, patterns, or collaborate with others!",
    ],
    enabled: true,
  },

  // ─── Phase 7: Logic, Educational & 3D Games ───
  {
    slug: "nerdle",
    title: "Nerdle",
    description: "Guess the hidden math equation in 6 tries. Each guess must be a valid 8-character equation. Green/yellow/gray hints guide you!",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/nerdle.png",
    color: "#7C3AED",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "hard",
    tags: ["math", "wordle", "logic", "deduction"],
    howToPlay: [
      "Guess the hidden 8-character math equation (e.g. 12+34=46)",
      "Each guess must be a valid equation using digits and +-*/=",
      "Green = correct position, Yellow = wrong position, Gray = not used",
      "You have 6 attempts to find the equation",
      "Score based on how few guesses you need",
    ],
    enabled: true,
  },
  {
    slug: "connections",
    title: "Connections",
    description: "Find four groups of four words that share a hidden connection. Be careful — there are tricky red herrings!",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/connections.png",
    color: "#CA8A04",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-10 min",
    difficulty: "medium",
    tags: ["words", "categories", "deduction"],
    howToPlay: [
      "16 words are displayed in a 4x4 grid",
      "Find 4 groups of 4 words that share a connection",
      "Select 4 words and submit your guess",
      "You have 4 mistakes allowed before game over",
      "Harder groups are worth more points",
    ],
    enabled: true,
  },
  {
    slug: "lights-out",
    title: "Lights Out",
    description: "Toggle lights on a 5x5 grid — clicking a light flips it and its neighbors. Turn them all off to win!",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/lights-out.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "2-5 min",
    difficulty: "medium",
    tags: ["logic", "grid", "classic"],
    howToPlay: [
      "Click any light to toggle it and its adjacent neighbors",
      "Your goal is to turn ALL lights off",
      "Fewer moves = higher score",
      "Each level starts with a solvable configuration",
      "Plan ahead — some moves affect many lights!",
    ],
    enabled: true,
  },
  {
    slug: "kenken",
    title: "KenKen",
    description: "Fill a Latin square grid with numbers, following cage arithmetic constraints. Like Sudoku meets math!",
    category: "puzzle",
    scoreType: "time",
    renderingMode: "dom",
    thumbnail: "/games/kenken.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-15 min",
    difficulty: "hard",
    tags: ["math", "logic", "grid", "puzzle"],
    howToPlay: [
      "Fill each row and column with numbers 1-4 (no repeats)",
      "Outlined cages show a target number and operation (+, -, ×, ÷)",
      "Numbers in each cage must combine to reach the target",
      "Click a cell and type a number to fill it in",
      "Complete the grid as fast as possible!",
    ],
    enabled: true,
  },
  {
    slug: "monty-hall",
    title: "Monty Hall",
    description: "The classic probability puzzle! Pick a door, one is revealed, then decide — stick or switch?",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/monty-hall.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "easy",
    tags: ["probability", "statistics", "classic"],
    howToPlay: [
      "Three doors hide a prize behind one of them",
      "Pick a door, then the host reveals a losing door",
      "Choose to STICK with your pick or SWITCH to the other",
      "Play 20 rounds and track your win rate",
      "Discover why switching wins 2/3 of the time!",
    ],
    enabled: true,
  },
  {
    slug: "dice-trader",
    title: "Dice Trader",
    description: "Roll dice and make strategic trades to maximize your score. Push your luck or play it safe!",
    category: "arcade",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/dice-trader.png",
    color: "#CA8A04",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "easy",
    tags: ["dice", "luck", "strategy"],
    howToPlay: [
      "Roll 5 dice each round",
      "Lock dice you want to keep, re-roll the rest (up to 2 re-rolls)",
      "Score points based on combinations (pairs, straights, etc.)",
      "Play 10 rounds to maximize your total score",
      "Higher combinations = bigger points!",
    ],
    enabled: true,
  },
  {
    slug: "sequence-solver",
    title: "Sequence Solver",
    description: "Identify the pattern and predict the next number in the sequence. How many can you solve?",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/sequence-solver.png",
    color: "#7C3AED",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "medium",
    tags: ["math", "patterns", "logic"],
    howToPlay: [
      "A number sequence is shown with the last number hidden",
      "Figure out the pattern and type your answer",
      "Each correct answer earns points (harder = more points)",
      "Wrong answers skip to the next sequence",
      "Solve 10 sequences to finish the game",
    ],
    enabled: true,
  },
  {
    slug: "logic-grid",
    title: "Logic Grid",
    description: "Solve logic grid puzzles using clues to match items across categories. Pure deduction!",
    category: "puzzle",
    scoreType: "time",
    renderingMode: "dom",
    thumbnail: "/games/logic-grid.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-15 min",
    difficulty: "hard",
    tags: ["logic", "deduction", "grid"],
    howToPlay: [
      "Match items across 3 categories using the provided clues",
      "Click grid cells to mark YES (green) or NO (red)",
      "Use elimination — if one match is found, cross out others",
      "Read clues carefully for direct and indirect information",
      "Solve the entire grid as fast as possible!",
    ],
    enabled: true,
  },
  {
    slug: "nonogram",
    title: "Nonogram",
    description: "Reveal a hidden picture by filling cells according to row and column number clues.",
    category: "puzzle",
    scoreType: "time",
    renderingMode: "canvas",
    thumbnail: "/games/nonogram.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-15 min",
    difficulty: "hard",
    tags: ["pixel", "logic", "picture"],
    howToPlay: [
      "Numbers on rows/columns show groups of consecutive filled cells",
      "Click to fill a cell, right-click to mark it empty (X)",
      "Use the number clues to deduce which cells to fill",
      "Complete the grid to reveal the hidden picture",
      "Faster completion = better score!",
    ],
    enabled: true,
  },
  {
    slug: "memory-matrix",
    title: "Memory Matrix",
    description: "Memorize the pattern, then recreate it from memory. How far can your visual memory go?",
    category: "arcade",
    scoreType: "points",
    renderingMode: "dom",
    thumbnail: "/games/memory-matrix.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "medium",
    tags: ["memory", "visual", "pattern"],
    howToPlay: [
      "A pattern of highlighted cells flashes briefly",
      "After it disappears, click the cells you remember",
      "Get it right to advance to a harder level",
      "Grid size and pattern complexity increase each round",
      "One mistake and it's game over!",
    ],
    enabled: true,
  },
  {
    slug: "cube-roll",
    title: "Cube Roll",
    description: "Roll a cube across a grid to reach the goal. Plan your moves — the top face color matters!",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "canvas",
    thumbnail: "/games/cube-roll.png",
    color: "#7C3AED",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-10 min",
    difficulty: "medium",
    tags: ["3d", "spatial", "puzzle"],
    howToPlay: [
      "Use arrow keys to roll the cube across the grid",
      "Reach the goal tile to complete each level",
      "The cube must land on the goal with the correct face up",
      "Avoid holes and obstacles in the grid",
      "Fewer moves = higher score!",
    ],
    enabled: true,
  },
  {
    slug: "marble-maze",
    title: "Marble Maze",
    description: "Tilt the maze to guide a marble to the goal. Real physics — avoid the holes!",
    category: "arcade",
    scoreType: "time",
    renderingMode: "canvas",
    thumbnail: "/games/marble-maze.png",
    color: "#DB2777",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "medium",
    tags: ["3d", "physics", "maze"],
    howToPlay: [
      "Use arrow keys or WASD to tilt the maze",
      "Guide the marble from start to the goal",
      "Avoid holes — falling in resets the level!",
      "Complete each level as fast as possible",
      "Physics-based movement — momentum matters!",
    ],
    enabled: true,
  },
  {
    slug: "tower-of-hanoi-3d",
    title: "Tower of Hanoi 3D",
    description: "The classic Tower of Hanoi puzzle in 3D. Move all disks to the target peg in minimum moves!",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "canvas",
    thumbnail: "/games/tower-of-hanoi-3d.png",
    color: "#CA8A04",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-10 min",
    difficulty: "medium",
    tags: ["3d", "classic", "logic"],
    howToPlay: [
      "Move all disks from the left peg to the right peg",
      "Click a peg to pick up its top disk, click another to place it",
      "You can never place a larger disk on a smaller one",
      "Try to solve it in the minimum number of moves (2^n - 1)",
      "Fewer moves = higher score!",
    ],
    enabled: true,
  },
  {
    slug: "sokoban-3d",
    title: "3D Sokoban",
    description: "Push crates onto goal tiles in this 3D puzzle. Plan carefully — you can only push, not pull!",
    category: "puzzle",
    scoreType: "points",
    renderingMode: "canvas",
    thumbnail: "/games/sokoban-3d.png",
    color: "#16A34A",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-15 min",
    difficulty: "hard",
    tags: ["3d", "sokoban", "puzzle"],
    howToPlay: [
      "Use arrow keys to move your character",
      "Push crates onto the glowing goal tiles",
      "You can only push — never pull — one crate at a time",
      "Don't push crates into corners or against walls!",
      "Complete each level in minimum moves for max score",
    ],
    enabled: true,
  },
  {
    slug: "orbit-architect",
    title: "Orbit Architect",
    description: "Place planets and set velocities to create stable orbital systems. N-body gravity simulation!",
    category: "creative",
    scoreType: "points",
    renderingMode: "canvas",
    thumbnail: "/games/orbit-architect.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "5-10 min",
    difficulty: "hard",
    tags: ["3d", "physics", "space", "creative"],
    howToPlay: [
      "Place planets around a central star by clicking in space",
      "Drag to set each planet's initial velocity",
      "Press Play to start the N-body gravity simulation",
      "Planets that survive 30 seconds earn stability points",
      "More planets in stable orbits = higher score!",
    ],
    enabled: true,
  },

  // ─── Phase 6: 3D Racing ───
  {
    slug: "velocity",
    title: "Velocity.js",
    description:
      "Race through neon-lit circuits at breakneck speed. Drift around corners, boost past opponents, and cross the finish line first!",
    category: "arcade",
    scoreType: "time",
    renderingMode: "canvas",
    thumbnail: "/games/velocity.png",
    color: "#0891B2",
    minPlayers: 1,
    maxPlayers: 1,
    estimatedPlayTime: "3-5 min",
    difficulty: "medium",
    tags: ["racing", "3d", "arcade", "drift"],
    howToPlay: [
      "W / Arrow Up = Accelerate, S / Arrow Down = Brake",
      "A / Arrow Left = Steer Left, D / Arrow Right = Steer Right",
      "Hold Space while turning to drift — release for a speed boost!",
      "Complete 3 laps around the neon track to finish",
      "Hit boost pads for a burst of speed, avoid barriers!",
      "Your score is your total race time — faster is better",
    ],
    enabled: true,
  },
];

export function getGameBySlug(slug: string): GameConfig | undefined {
  return gameRegistry.find((g) => g.slug === slug);
}

export function getEnabledGames(): GameConfig[] {
  return gameRegistry.filter((g) => g.enabled);
}

export function getGamesByCategory(category: string): GameConfig[] {
  return gameRegistry.filter((g) => g.category === category && g.enabled);
}
